# Generated by Django 5.2.11 on 2026-03-07 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_add_sentiment'),
        ('feedback', '0002_alter_form_description'),
    ]

    operations = [
    ]
