# Generated by Django 5.2.11 on 2026-03-07 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_merge_0002_add_sentiment_0002_alter_form_description'),
        ('feedback', '0003_sentiment_and_calculate_stats'),
    ]

    operations = [
    ]
