# Generated by Django 5.2.11 on 2026-04-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_merge_20260307_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='responseanswer',
            name='ai_issues',
            field=models.TextField(blank=True, help_text='Detected product/service issues', null=True),
        ),
        migrations.AddField(
            model_name='responseanswer',
            name='ai_suggestions',
            field=models.TextField(blank=True, help_text='Suggested product/service improvements', null=True),
        ),
        migrations.AddField(
            model_name='responseanswer',
            name='form_improvements',
            field=models.TextField(blank=True, help_text='Suggested improvements for form quality', null=True),
        ),
        migrations.AddField(
            model_name='responseanswer',
            name='form_issues',
            field=models.TextField(blank=True, help_text='Detected issues with the form itself', null=True),
        ),
    ]
